apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
spec:
  template:
    spec:
      containers:
      - name: katib-db-manager
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: DB_NAME
          - name: KATIB_MYSQL_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: KATIB_MYSQL_DB_DATABASE
          - name: KATIB_MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: MYSQL_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: DB_PASSWORD
